import { Container } from '@mui/material';
import React, { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import usePagination from '../../../../utils/usePagination';
import SearchHeader from '../../components/SearchHeader/SearchHeader';
import SearchList from '../../components/SearchList/SearchList';
import SearchPagination from '../../components/SearchPagination/SearchPagination';
import SearchTitle from '../../components/SearchTitle/SearchTitle';
import productImage from '../../../../../images/Rolex01.jpg';

Search.propTypes = {};

const initList = [
  {
    id: 1,
    name: 'Đồng hồ Rolex chính hãng 12345',
    price: 1,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 2,
    name: 'Đồng hồ Rolex chính hãng 9999',
    price: 4,
    src: productImage,
    desc: 'Automatic',
    categoryId: 2,
  },
  {
    id: 3,
    name: 'Đồng hồ Rolex chính hãng 12345',
    price: 5,
    src: productImage,
    desc: 'Automatic',
    categoryId: 3,
  },
  {
    id: 4,
    name: 'Đồng hồ Rolex chính hãng',
    price: 3,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 5,
    name: 'Đồng hồ Rolex chính hãng 12345',
    price: 4,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 6,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 2,
  },
  {
    id: 7,
    name: 'Đồng hồ Rolex chính hãng',
    price: 3,
    src: productImage,
    desc: 'Automatic',
    categoryId: 3,
  },
  {
    id: 8,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 9,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 10,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 2,
  },
  {
    id: 11,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 3,
  },
  {
    id: 12,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 13,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 14,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 2,
  },
  {
    id: 15,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 3,
  },
  {
    id: 16,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 17,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 18,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 2,
  },
  {
    id: 19,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 3,
  },
  {
    id: 20,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 21,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 22,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 23,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 24,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 25,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 26,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 27,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 28,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 29,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 30,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 31,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 32,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 33,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 34,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 35,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 36,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 37,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 38,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 39,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 40,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 41,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 42,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 43,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 44,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 45,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 46,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 47,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 48,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 49,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 50,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 51,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 52,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 53,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 54,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 55,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 56,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 57,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 58,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 59,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 60,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 61,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 62,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 63,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 64,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 65,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 66,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 67,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 68,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 69,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 70,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 71,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 72,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 73,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 74,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 75,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 76,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 77,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
  {
    id: 78,
    name: 'Đồng hồ Rolex chính hãng',
    price: 1000000,
    src: productImage,
    desc: 'Automatic',
    categoryId: 1,
  },
];

function Search(props) {
  const [list, setList] = useState(initList);
  const [page, setPage] = useState(1);
  const [searchParams] = useSearchParams();
  const PER_PAGE = 12;

  const count = Math.ceil(list.length / PER_PAGE) || 1;
  const _LIST = usePagination(list, PER_PAGE);

  const handlePaginationChange = (e, page) => {
    setPage(page);
    _LIST.jump(page);
  };

  useEffect(() => {
    setList(
      initList.filter((x) =>
        x.name.toLowerCase().includes(searchParams.get('q')?.toLowerCase().trim())
      )
    );
  }, [searchParams.get('q')]);

  return (
    <Container>
      <SearchHeader />
      <SearchTitle length={list.length} text={searchParams.get('q')} />
      <SearchList list={_LIST.currentData()} />
      <SearchPagination count={count} page={page} onChange={handlePaginationChange} />
    </Container>
  );
}

export default Search;
